import {
  StatCardItem,
  ActivityItem,
  JobItem,
  CompanyItem,
  ApplicantItem,
  MessageThread,
  NewsItem,
  SystemUser,
} from '../types/admin';

export const INITIAL_STAT_CARDS: StatCardItem[] = [
  {
    id: 'stat-1',
    title: 'Interviews Schedule',
    value: '86',
    change: '+14% vs last week',
    iconName: 'calendar',
    bgGradient: 'from-[#4d33eb] to-[#4023d8]',
    pillColor: 'bg-white/20 text-white',
  },
  {
    id: 'stat-2',
    title: 'Application Sent',
    value: '75',
    change: '+8% this month',
    iconName: 'briefcase',
    bgGradient: 'from-[#2799ff] to-[#1283e8]',
    pillColor: 'bg-white/20 text-white',
  },
  {
    id: 'stat-3',
    title: 'Profile Viewed',
    value: '45,673',
    change: '+24.5k new hits',
    iconName: 'user',
    bgGradient: 'from-[#00d68f] to-[#00be7e]',
    pillColor: 'bg-white/20 text-white',
  },
  {
    id: 'stat-4',
    title: 'Unread Message',
    value: '93',
    change: '14 urgent inquiries',
    iconName: 'mail',
    bgGradient: 'from-[#8de02c] to-[#79cc1e]',
    pillColor: 'bg-white/20 text-white',
  },
];

export const INITIAL_ACTIVITIES: ActivityItem[] = [
  {
    id: 'act-1',
    title: 'Your application has accepted in 3 Vacancy',
    time: '12m ago',
    type: 'application',
  },
  {
    id: 'act-2',
    title: 'Your application has accepted in 3 Vacancy',
    time: '17m ago',
    type: 'application',
  },
  {
    id: 'act-3',
    title: 'Your application has accepted in 3 Vacancy',
    time: '12h ago',
    type: 'application',
  },
  {
    id: 'act-4',
    title: 'Your application has accepted in 3 Vacancy',
    time: '1d ago',
    type: 'application',
  },
  {
    id: 'act-5',
    title: 'Candidate Sarah Lin confirmed technical interview',
    time: '2d ago',
    type: 'interview',
  },
];

export const INITIAL_JOBS: JobItem[] = [
  {
    id: 'job-1',
    title: 'Database Programmer',
    company: 'Maximo Team',
    companyLogoColor: 'bg-blue-600',
    companyLogoLetter: 'C',
    salary: ',000 - ,000',
    type: 'Remote',
    location: 'London, England',
    tags: ['REMOTE', 'London, England'],
    applicantsCount: 38,
    status: 'active',
    description: 'We are seeking an experienced Database Programmer to architect high-performance PostgreSQL and MongoDB clusters with automated replication.',
    requirements: ['5+ years SQL/NoSQL', 'Database tuning & indexing', 'Docker & Kubernetes knowledge'],
    postedDate: '2 days ago',
  },
  {
    id: 'job-2',
    title: 'Senior Programmer',
    company: 'Xleon n Clin Studios',
    companyLogoColor: 'bg-orange-500',
    companyLogoLetter: 'C',
    salary: ',000 - ,000',
    type: 'Part-Time',
    location: 'Manchester, England',
    tags: ['PART TIME', 'Manchester, England'],
    applicantsCount: 52,
    status: 'active',
    description: 'Looking for a Senior TypeScript and Node.js engineer to build real-time collaborative applications with distributed web architectures.',
    requirements: ['React 18 & Node.js', 'Framer Motion & Tailwind', 'Microservices design'],
    postedDate: '3 days ago',
  },
  {
    id: 'job-3',
    title: 'Intern UX Designer',
    company: 'Maximo Team',
    companyLogoColor: 'bg-orange-500',
    companyLogoLetter: 'C',
    salary: ',000 - ,000',
    type: 'Full-Time',
    location: 'London, England',
    tags: ['FULTIME', 'London, England'],
    applicantsCount: 24,
    status: 'active',
    description: 'Exciting opportunity for a passionate UX/UI designer to build next-generation interfaces for enterprise enterprise cloud portals.',
    requirements: ['Figma prototyping', 'Design systems thinking', 'Mobile-first UX design'],
    postedDate: '5 days ago',
  },
  {
    id: 'job-4',
    title: 'Lead AI Engineer',
    company: 'Techwiz Labs',
    companyLogoColor: 'bg-purple-600',
    companyLogoLetter: 'T',
    salary: ',000 - ,000',
    type: 'Remote',
    location: 'San Francisco, CA',
    tags: ['REMOTE', 'Full-Time'],
    applicantsCount: 61,
    status: 'active',
    description: 'Develop and fine-tune large language model agents and multimodal generative pipelines for high-throughput production workloads.',
    requirements: ['Python & PyTorch', 'LangChain / Agentic RAG', 'FastAPI backend'],
    postedDate: '1 day ago',
  },
  {
    id: 'job-5',
    title: 'DevOps & Cloud Architect',
    company: 'CloudMatrix Global',
    companyLogoColor: 'bg-emerald-600',
    companyLogoLetter: 'M',
    salary: ',000 - ,000',
    type: 'Full-Time',
    location: 'Berlin, Germany',
    tags: ['FULLTIME', 'Hybrid'],
    applicantsCount: 19,
    status: 'active',
    description: 'Lead AWS infrastructure provisioning using Terraform, manage CI/CD GitHub Action runners, and ensure zero-downtime blue/green deployments.',
    requirements: ['AWS / GCP Certified', 'Terraform & Helm', 'Prometheus & Grafana'],
    postedDate: '4 days ago',
  },
];

export const INITIAL_COMPANIES: CompanyItem[] = [
  {
    id: 'comp-1',
    name: 'Herman-Carter',
    logoColor: 'bg-[#00c9db]',
    logoLetter: 'C',
    vacancies: 21,
    location: 'London, UK',
    industry: 'Fintech & Security',
  },
  {
    id: 'comp-2',
    name: 'Funk Inc.',
    logoColor: 'bg-[#55ba45]',
    logoLetter: 'C',
    vacancies: 21,
    location: 'Austin, TX',
    industry: 'Creative Media',
  },
  {
    id: 'comp-3',
    name: 'Williamson Inc',
    logoColor: 'bg-[#e5ab1b]',
    logoLetter: 'C',
    vacancies: 21,
    location: 'Toronto, Canada',
    industry: 'Enterprise Software',
  },
  {
    id: 'comp-4',
    name: 'Donnelly Ltd.',
    logoColor: 'bg-[#e92b8d]',
    logoLetter: 'C',
    vacancies: 21,
    location: 'Dublin, Ireland',
    industry: 'E-commerce & Logistics',
  },
  {
    id: 'comp-5',
    name: 'Herman-Carter',
    logoColor: 'bg-[#8944db]',
    logoLetter: 'C',
    vacancies: 21,
    location: 'Singapore',
    industry: 'Artificial Intelligence',
  },
];

export const INITIAL_APPLICANTS: ApplicantItem[] = [
  {
    id: 'app-1',
    name: 'Sarah Lin',
    avatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?q=80&w=200&auto=format&fit=crop',
    email: 'sarah.lin@example.com',
    phone: '+1 (555) 234-5678',
    appliedJobId: 'job-1',
    appliedJobTitle: 'Database Programmer',
    stage: 'interview',
    matchScore: 96,
    rating: 4.9,
    appliedDate: 'Aug 22, 2026',
    experience: '6 Years',
    skills: ['PostgreSQL', 'MongoDB', 'Redis', 'Python', 'Docker'],
    notes: 'Exceeded expectations in technical architectural assessment.',
  },
  {
    id: 'app-2',
    name: 'David Vance',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?q=80&w=200&auto=format&fit=crop',
    email: 'david.vance@example.com',
    phone: '+44 20 7946 0912',
    appliedJobId: 'job-2',
    appliedJobTitle: 'Senior Programmer',
    stage: 'screening',
    matchScore: 91,
    rating: 4.7,
    appliedDate: 'Aug 23, 2026',
    experience: '8 Years',
    skills: ['React', 'TypeScript', 'Node.js', 'GraphQL', 'AWS'],
    notes: 'Portfolio includes several high-scale fintech web apps.',
  },
  {
    id: 'app-3',
    name: 'Elena Rostova',
    avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?q=80&w=200&auto=format&fit=crop',
    email: 'elena.rostova@example.com',
    phone: '+49 30 901820',
    appliedJobId: 'job-3',
    appliedJobTitle: 'Intern UX Designer',
    stage: 'accepted',
    matchScore: 98,
    rating: 5.0,
    appliedDate: 'Aug 20, 2026',
    experience: '2 Years',
    skills: ['Figma', 'UI/UX', 'Design Systems', 'Prototyping', 'Tailwind'],
    notes: 'Offer letter signed. Starting onboarding on Sept 1st.',
  },
  {
    id: 'app-4',
    name: 'Marcus Chen',
    avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?q=80&w=200&auto=format&fit=crop',
    email: 'marcus.chen@example.com',
    phone: '+1 (555) 987-6543',
    appliedJobId: 'job-4',
    appliedJobTitle: 'Lead AI Engineer',
    stage: 'applied',
    matchScore: 88,
    rating: 4.5,
    appliedDate: 'Aug 24, 2026',
    experience: '5 Years',
    skills: ['PyTorch', 'Transformers', 'Agentic Workflows', 'Python'],
    notes: 'Reviewing recent publications on multi-agent collaboration.',
  },
  {
    id: 'app-5',
    name: 'Amira Patel',
    avatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?q=80&w=200&auto=format&fit=crop',
    email: 'amira.patel@example.com',
    phone: '+91 98765 43210',
    appliedJobId: 'job-1',
    appliedJobTitle: 'Database Programmer',
    stage: 'rejected',
    matchScore: 68,
    rating: 3.2,
    appliedDate: 'Aug 18, 2026',
    experience: '1 Year',
    skills: ['MySQL', 'Basic Python'],
    notes: 'Candidate needs more senior distributed systems experience.',
  },
];

export const INITIAL_THREADS: MessageThread[] = [
  {
    id: 'thread-1',
    contactName: 'Oda Dink',
    contactRole: 'Lead Programmer',
    avatar: 'https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?q=80&w=200&auto=format&fit=crop',
    lastMessage: 'I have reviewed the candidate applications for the Database vacancy.',
    time: '10:42 AM',
    unreadCount: 3,
    isOnline: true,
    messages: [
      {
        id: 'm-1',
        senderId: 'contact',
        senderName: 'Oda Dink',
        text: 'Hi there! Did you get a chance to inspect the new applicants from yesterday?',
        timestamp: '10:30 AM',
        isMe: false,
      },
      {
        id: 'm-2',
        senderId: 'me',
        senderName: 'Super Admin',
        text: 'Yes! Sarah Lin looks like an exceptional match for our Database role.',
        timestamp: '10:35 AM',
        isMe: true,
      },
      {
        id: 'm-3',
        senderId: 'contact',
        senderName: 'Oda Dink',
        text: 'I have reviewed the candidate applications for the Database vacancy. Scheduling interview now!',
        timestamp: '10:42 AM',
        isMe: false,
      },
    ],
  },
  {
    id: 'thread-2',
    contactName: 'Sarah Lin',
    contactRole: 'Applicant - Database Programmer',
    avatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?q=80&w=200&auto=format&fit=crop',
    lastMessage: 'Thank you for the interview invite! Looking forward to Thursday.',
    time: '9:15 AM',
    unreadCount: 1,
    isOnline: true,
    messages: [
      {
        id: 'm-4',
        senderId: 'contact',
        senderName: 'Sarah Lin',
        text: 'Thank you for the interview invite! Looking forward to Thursday.',
        timestamp: '9:15 AM',
        isMe: false,
      },
    ],
  },
  {
    id: 'thread-3',
    contactName: 'Herman-Carter HR',
    contactRole: 'Partner Recruiter',
    avatar: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?q=80&w=200&auto=format&fit=crop',
    lastMessage: 'We posted 5 new job openings on the portal this morning.',
    time: 'Yesterday',
    unreadCount: 0,
    isOnline: false,
    messages: [
      {
        id: 'm-5',
        senderId: 'contact',
        senderName: 'Herman-Carter HR',
        text: 'We posted 5 new job openings on the portal this morning.',
        timestamp: 'Yesterday',
        isMe: false,
      },
    ],
  },
];

export const INITIAL_NEWS: NewsItem[] = [
  {
    id: 'news-1',
    title: 'Techwiz 2026 Portal Major Upgrade Launched',
    summary: 'The all-new Jobie Admin Suite is now live with real-time candidate analytics and spline telemetry.',
    content: 'We are thrilled to unveil the new TicketToTechwiz administrative dashboard. This release includes high-frequency application monitoring, spline chart visualizations, multi-role authentication guards, and direct applicant messaging.',
    category: 'Update',
    author: 'Techwiz Core Team',
    authorRole: 'System Administrator',
    authorAvatar: 'https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?q=80&w=200&auto=format&fit=crop',
    date: 'Aug 24, 2026',
    views: 1420,
    likes: 89,
    tags: ['Release', 'Dashboard', 'Admin'],
    priority: 'featured',
  },
  {
    id: 'news-2',
    title: 'Annual Developer & Techwiz Summit Announced',
    summary: 'Join over 5,000 engineers and designers across the globe for workshops and live hackathons.',
    content: 'Registration opens next week for the flagship Techwiz annual engineering conference. Keynote topics include Generative Agentic Coding, Distributed Cloud Frameworks, and Modern Full-Stack Workflows.',
    category: 'Event',
    author: 'Elena Rostova',
    authorRole: 'Event Lead',
    authorAvatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?q=80&w=200&auto=format&fit=crop',
    date: 'Aug 23, 2026',
    views: 890,
    likes: 64,
    tags: ['Event', 'Conference', 'Hackathon'],
    priority: 'normal',
  },
  {
    id: 'news-3',
    title: 'Security Advisory: Multi-Factor & JWT Token Hardening',
    summary: 'Updated guidelines for JWT session revocation and OAuth token rotation in production environments.',
    content: 'All administrative accounts are now protected with enhanced cryptographic token validations and role-based route middleware checks.',
    category: 'System',
    author: 'Security Ops',
    authorRole: 'Chief Security Officer',
    authorAvatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?q=80&w=200&auto=format&fit=crop',
    date: 'Aug 21, 2026',
    views: 654,
    likes: 41,
    tags: ['Security', 'JWT', 'Best Practices'],
    priority: 'urgent',
  },
];

export const INITIAL_USERS: SystemUser[] = [
  {
    id: 'u-1',
    email: 'admin@techwiz.com',
    displayName: 'Administrator',
    role: 'admin',
    status: 'active',
    lastActive: 'Active in MongoDB Atlas',
    avatar: 'https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?q=80&w=200&auto=format&fit=crop',
  },
  {
    id: 'u-2',
    email: 'customer@techwiz.com',
    displayName: 'Techwiz Customer',
    role: 'customer',
    status: 'active',
    lastActive: 'Active in MongoDB Atlas',
    avatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?q=80&w=200&auto=format&fit=crop',
  },
];

// LocalStorage Persistence helpers
const STORAGE_PREFIX = 'techwiz_admin_';

export const getStoredData = <T>(key: string, fallback: T): T => {
  try {
    const item = localStorage.getItem(STORAGE_PREFIX + key);
    return item ? JSON.parse(item) : fallback;
  } catch {
    return fallback;
  }
};

export const setStoredData = <T>(key: string, data: T): void => {
  try {
    localStorage.setItem(STORAGE_PREFIX + key, JSON.stringify(data));
  } catch (err) {
    console.error('Failed to save to localStorage', err);
  }
};
